CREATE TABLE STUDENT
(
    USERNAME     VARCHAR(30) PRIMARY KEY,
    STUID        VARCHAR(20),
    NAME         VARCHAR(10),
    PEOPLE       INT,
    INCOME       DOUBLE,
    COSTFORFOOD  DOUBLE,
    COSTFOROTHER DOUBLE
);
CREATE TABLE USER
(
    USERNAME VARCHAR(30) PRIMARY KEY,
    PASSWORD CHAR(64),
    ADMIN    INT
);
CREATE TABLE SUBMIT
(
    USERNAME VARCHAR(30) PRIMARY KEY,
    ANSWER   INT
);